
language: php

jobs:
  include:
    - os: linux
      distro: precise
      php:
        - 5.3
        - 5.4
        - 5.5
        - 5.6
        - 7.0
    - os: linux
      distro: xenial
      php:
        - 7.0
        - 7.1
        - 7.2
        - 7.3
        - 7.4
        - nightly
    - os: linux
      distro: bionic
      php:
        - 7.0
        - 7.1
        - 7.2
        - 7.3
        - 7.4
        - nightly

env:
    matrix:
      - ENABLE_MAINTAINER_ZTS=0 ENABLE_DEBUG=0
      - ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1
      - ENABLE_MAINTAINER_ZTS=1 ENABLE_DEBUG=1 USE_ZEND_ALLOC=0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes valgrind

script: sh ci/run-test.sh
